######################################################################
#
# File name : uart_byte_tx_tb_wave.do
# Created on: Tue Sep 10 11:22:52 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
