######################################################################
#
# File name : uart_byte_tx_tb_compile.do
# Created on: Thu Sep 12 11:27:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../uart_tx.srcs/sources_1/ip/vio_0/hdl" \
"../../../../uart_tx.srcs/sources_1/new/uart_byte_tx.v" \
"../../../../uart_tx.srcs/sim_1/new/uart_byte_tx_tb.v" \


# compile glbl module
E:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

