######################################################################
#
# File name : uart_byte_tx_tb_simulate.do
# Created on: Thu Sep 12 11:28:03 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.uart_byte_tx_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {uart_byte_tx_tb_wave.do}

view wave
view structure
view signals

do {uart_byte_tx_tb.udo}

run 1000ns
