set_property SRC_FILE_INFO {cfile:H:/my_workshop/learn_fpga/prj/bin_counter/bin_counter.srcs/constrs_1/new/bin_counter.xdc rfile:../../../bin_counter.srcs/constrs_1/new/bin_counter.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports led]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports reset_n]
