set_property SRC_FILE_INFO {cfile:H:/my_workshop/learn_fpga/prj/led_flash/led_flash.srcs/constrs_1/new/led_flash.xdc rfile:../../../led_flash.srcs/constrs_1/new/led_flash.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports led]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports rst_n]
