######################################################################
#
# File name : bin_counter_tb_wave.do
# Created on: Thu Sep 05 13:33:27 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
