######################################################################
#
# File name : bin_counter_tb_simulate.do
# Created on: Thu Sep 05 13:39:37 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -coverage -fsmdebug -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.bin_counter_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {bin_counter_tb_wave.do}

view wave
view structure
view signals

do {bin_counter_tb.udo}

run 1000ns
