######################################################################
#
# File name : led_flash_wave.do
# Created on: Fri Aug 30 08:46:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
