######################################################################
#
# File name : led_flash_simulate.do
# Created on: Thu Sep 05 08:38:30 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -coverage -fsmdebug -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.led_flash xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {led_flash_wave.do}

view wave
view structure
view signals

do {led_flash.udo}

run 1000ns
