######################################################################
#
# File name : bin_counter_tb.udo
# Created on: Thu Sep 05 13:33:27 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
