######################################################################
#
# File name : bin_counter_tb_compile.do
# Created on: Mon Sep 09 14:39:38 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../bin_counter.srcs/sources_1/new/bin_counter.v" \
"../../../../bin_counter.srcs/sim_1/new/bin_counter_tb.v" \


# compile glbl module
E:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

