######################################################################
#
# File name : led_flash_compile.do
# Created on: Thu Sep 05 08:38:28 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../led_flash.srcs/sources_1/new/led_flash.v" \


# compile glbl module
E:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

